return {
 
  -- { -- Copilot Lua
  --   "zbirenbaum/copilot.lua",
  --   event = "InsertEnter",
  --   config = function()
  --     require("copilot").setup({
  --       suggestion = {
  --         enabled = true,
  --         auto_trigger = false,
  --         hide_during_completion = true,
  --         debounce = 75,
  --         trigger_on_accept = true,
  --         keymap = {
  --           accept = "<M-l>",
  --           accept_word = "<M-w>",
  --           accept_line = "<M-;>",
  --           next = "<M-]>",
  --           prev = "<M-[>",
  --           dismiss = "<C-]>",
  --         },
  --       },
  --       filetypes = {
  --         tex = false,
  --         yaml = false,
  --         markdown = false,
  --         help = false,
  --         gitcommit = false,
  --         gitrebase = false,
  --         hgcommit = false,
  --         svn = false,
  --         cvs = false,
  --         text = false,
  --         txt = false,
  --         ocaml = false,
  --         ["."] = false,
  --       },
  --       copilot_node_command = "node", -- Node.js version must be > 20
  --     })
  --   end,
  -- },
  --
  -- { -- Copilot CMP
  --   "zbirenbaum/copilot-cmp",
  --
  --   config = function()
  --     require("copilot_cmp").setup()
  --   end,
  -- },

}

